# Generated by Django 2.2.16 on 2022-03-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
